apiVersion:  apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: monitoring
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
      app: monitoring
  template:
    metadata:
      labels:
        name: grafana
        app: monitoring
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
          - containerPort: 3000
          
